kafka:
  bootstrap-servers: localhost:9092
  topic: my-replicated-topic


swagger:
  title: Formation KAFKA
  description: Swagger Documentation api for Formation KAFKA PRODUCER application
  version: @project.version@
  enabled: true

server:
  port: 8077
