kafka:
  bootstrap-servers: localhost:9092
  topic: my-replicated-topic


swagger:
  title: Formation KAFKA
  description: Swagger Documentation api for Formation KAFKA PRODUCER application
  version: 1.0-SNAPSHOT
  enabled: true

server:
  port: 8077
